branch-defaults:
  dev:
    environment: StatSmash
    group_suffix: null
environment-defaults:
  StatSmash:
    branch: null
    repository: null
global:
  application_name: StatSmash
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: python2.7
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
